stages:
  - test

test:
  stage: test
  image: $IMAGE
  script:
    - pip install tox
    - tox --skip-missing-interpreters
  parallel:
    matrix:
      - IMAGE:
          - python:3.7
          - python:3.8
          - python:3.9
