stages:
  - test

include:
  - project: thelabnyc/gitlab-ci-templates
    file: /ci/sast.gitlab-ci.yml

test_python36:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox --skip-missing-interpreters

test_python37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox --skip-missing-interpreters

test_python38:
  stage: test
  image: python:3.8
  script:
    - pip install tox
    - tox --skip-missing-interpreters
