[tox]
isolated_build = True
toxworkdir={env:TOX_WORK_DIR:.tox}
envlist = py{311,312,313,314}-wagtail{70,74}

[testenv]
runner = uv-venv-runner
allowlist_externals =
    bash
deps =
    wagtail70: wagtail>=7.0,<7.1
    wagtail74: wagtail>=7.4,<7.5
setenv =
    PYTHONWARNINGS = d
commands =
    mypy wagtail_draftail_plugins
